# Generated by Django 5.2.4 on 2025-07-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('product_node_level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('commercial_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.CharField(max_length=100)),
                ('service_channel', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('fee_type', models.CharField(blank=True, max_length=50)),
                ('applicable_for_institutions', models.JSONField(blank=True, default=list)),
                ('last_modification_date_time', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=10)),
                ('target_currency', models.CharField(max_length=10)),
                ('conversion_value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('inverse_conversion_value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('effective_date', models.DateTimeField()),
                ('last_effective_date_time', models.DateTimeField(blank=True, null=True)),
                ('min_conversion_value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('max_conversion_value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.financialproduct')),
            ],
        ),
    ]
