# Generated by Django 5.2.4 on 2025-07-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fxrate',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('InstitutionType', models.CharField(blank=True, max_length=20, null=True)),
                ('BIC_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.address')),
            ],
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='FinancialInstitution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.financialinstitution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxrate',
            name='FinancialInstitution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.financialinstitution'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
