# Generated by Django 5.2.4 on 2025-07-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_address_remove_fxrate_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('account_status', models.CharField(blank=True, max_length=50)),
                ('account_currency', models.CharField(blank=True, max_length=10)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.financialinstitution')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.financialproduct')),
            ],
        ),
    ]
